[package]
name = "exchange_rate_web"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3.7" #web框架
tokio = {version = "1.40.0",features = ["full"]} #异步运行
reqwest = {version = "0.12.8",features = ["json"]}
serde ={version = "1.0.210",features = ["derive"]}
